using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SQLHibernate.Define.SQLServer
{
    [FlagsAttribute]
    public enum FieldFlags
    {
        // Field is not used
        None = 0,
        // Field can be read from the database.
        Read = 1,
        // Field can be written to the database.
        Write = 2,
        // Field can be read and written. Same as Read | Write.
        ReadWrite = 3,
        // Field is, or part of, the primary key.
        Key = 4,
        // Field's value is auto generated by the database.
        Auto = 8
    }
}
