// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EditFormTemplate : SharedFormGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
 var EntityName = Table.BindingName; 
            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentModel;\r\nu" +
                    "sing System.Data;\r\nusing System.Drawing;\r\nusing System.Runtime.CompilerServices;" +
                    "\r\nusing System.Text;\r\nusing System.Windows.Forms;\r\nusing ");
            
            #line 15 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.ProjectOwner.DefaultModelNamespaces));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 17 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
 Write(Generator.Namespace); 
            
            #line default
            #line hidden
            this.Write("{\r\n    public partial class Edit");
            
            #line 19 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Form : Edit");
            
            #line 19 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("FormBase\r\n    {\r\n        public Edit");
            
            #line 21 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Form()\r\n        {\r\n            InitializeComponent();\r\n        }\r\n\r\n\t\t protected " +
                    "override void InitBinder(");
            
            #line 26 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(@" entity)
        {
            base.InitBinder(entity);
			
        }
    }

    // This additional inheritance is required to avoid a WinForms bug,
    // which does not allow using generic classes as base classes for forms and uer controls.
	
    public class Edit");
            
            #line 36 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("FormBase: EditDataForm<");
            
            #line 36 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(", Edit");
            
            #line 36 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Form> { }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
