// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditDataFormTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EditDataFormTemplate : SharedFormTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentModel;\r\nu" +
                    "sing System.Data;\r\nusing System.Drawing;\r\nusing System.Runtime.CompilerServices;" +
                    "\r\nusing System.Text;\r\nusing System.Windows.Forms;\r\nusing ");
            
            #line 14 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditDataFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.ProjectOwner.DefaultModelNamespaces));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 16 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditDataFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class EditDataForm<E, F> : BaseForm\r\n        where E: Bas" +
                    "eModel, new()\r\n        where F: EditDataForm<E, F>, new()\r\n    {\r\n        privat" +
                    "e Action<E> _saveAction;\r\n        protected BindingSource bindingSourceItem = ne" +
                    "w BindingSource();\r\n\r\n        public EditDataForm()\r\n        {\r\n            Init" +
                    "ializeComponent();\r\n        }\r\n\r\n        private static F SetUpForm(E entity, Ac" +
                    "tion<E> saveAction)\r\n        {\r\n            if (entity == null)\r\n               " +
                    " entity = new E();\r\n\r\n            F f = new F();\r\n            f.InitBinder(entit" +
                    "y);\r\n            f._saveAction = saveAction;\r\n\t\t\treturn f;\r\n        }\r\n\r\n       " +
                    " public static void Edit(E entity, Action<E> saveAction)\r\n        {\r\n           " +
                    " F f = SetUpForm(entity, saveAction);\r\n\t\t\tf.OnFormLoaded(f, FormType.FormUpdate)" +
                    ";\r\n            f.ShowDialog();\r\n        }\r\n\r\n        public static void Add(Acti" +
                    "on<E> saveAction)\r\n        {\r\n            F f = SetUpForm(null, saveAction);\r\n  " +
                    "          f.OnFormLoaded(f, FormType.FormAdd);\r\n            f.ShowDialog();\r\n   " +
                    "     }\r\n\r\n        protected virtual void OnFormLoaded(object sender, FormType e)" +
                    "\r\n        {\r\n        }\r\n\r\n        protected virtual void InitBinder(E entity)\r\n " +
                    "       {\r\n            bindingSourceItem.DataSource = entity;\r\n        }\r\n\r\n     " +
                    "   private void SaveChange()\r\n        {\r\n            var item = bindingSourceIte" +
                    "m.Current as E;\r\n            item.EndEdit();\r\n            _saveAction.Invoke(ite" +
                    "m);\r\n        }\r\n\r\n        private void UndoChange()\r\n        {\r\n            var " +
                    "item = bindingSourceItem.Current as E;\r\n            item.CancelEdit();\r\n        " +
                    "}\r\n\r\n        private void toolStripButtonSave_Click(object sender, EventArgs e)\r" +
                    "\n        {\r\n\t\t\tValidate();\r\n            SaveChange();\r\n            this.Close();" +
                    "\r\n        }\r\n\r\n        private void toolStripButtonUndo_Click(object sender, Eve" +
                    "ntArgs e)\r\n        {\r\n            UndoChange();\r\n        }\r\n    }\r\n\r\n    public " +
                    "enum FormType\r\n    {\r\n        FormAdd,\r\n        FormUpdate\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
