// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\EditDataFormDesignerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EditDataFormDesignerTemplate : SharedFormDesignerGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// using DemoGeneratedProject.DTO;\r\n\r\nnamespace ");
            
            #line 8 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\EditDataFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    partial class EditDataForm<E, F>\r\n    {\r\n        /// <summary>\r\n        " +
                    "/// Required designer variable.\r\n        /// </summary>\r\n        private System." +
                    "ComponentModel.IContainer components = null;\r\n\r\n        /// <summary>\r\n        /" +
                    "// Clean up any resources being used.\r\n        /// </summary>\r\n        /// <para" +
                    "m name=\"disposing\">true if managed resources should be disposed; otherwise, fals" +
                    "e.</param>\r\n        protected override void Dispose(bool disposing)\r\n        {\r\n" +
                    "            if (disposing && (components != null))\r\n            {\r\n             " +
                    "   components.Dispose();\r\n            }\r\n            base.Dispose(disposing);\r\n " +
                    "       }\r\n\r\n        #region Windows Form Designer generated code\r\n\r\n        /// " +
                    "<summary>\r\n        /// Required method for Designer support - do not modify\r\n   " +
                    "     /// the contents of this method with the code editor.\r\n        /// </summar" +
                    "y>\r\n        private void InitializeComponent()\r\n        {\r\n            this.tool" +
                    "Strip1 = new System.Windows.Forms.ToolStrip();\r\n            this.toolStripButton" +
                    "Save = new System.Windows.Forms.ToolStripButton();\r\n            this.toolStripBu" +
                    "ttonUndo = new System.Windows.Forms.ToolStripButton();\r\n            this.toolStr" +
                    "ip1.SuspendLayout();\r\n            this.SuspendLayout();\r\n            // \r\n      " +
                    "      // toolStrip1\r\n            // \r\n            this.toolStrip1.Items.AddRange" +
                    "(new System.Windows.Forms.ToolStripItem[] {\r\n            this.toolStripButtonSav" +
                    "e,\r\n            this.toolStripButtonUndo});\r\n            this.toolStrip1.Locatio" +
                    "n = new System.Drawing.Point(0, 0);\r\n            this.toolStrip1.Name = \"toolStr" +
                    "ip1\";\r\n            this.toolStrip1.Size = new System.Drawing.Size(234, 25);\r\n   " +
                    "         this.toolStrip1.TabIndex = 6;\r\n            this.toolStrip1.Text = \"tool" +
                    "Strip1\";\r\n            // \r\n            // toolStripButtonSave\r\n            // \r\n" +
                    "            this.toolStripButtonSave.DisplayStyle = System.Windows.Forms.ToolStr" +
                    "ipItemDisplayStyle.Text;\r\n            //this.toolStripButtonSave.Image = global:" +
                    ":");
            
            #line 58 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\EditDataFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write(@".Properties.Resources.Save_16x;
            this.toolStripButtonSave.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonSave.Name = ""toolStripButtonSave"";
            this.toolStripButtonSave.Size = new System.Drawing.Size(35, 22);
            this.toolStripButtonSave.Text = ""Save"";
            this.toolStripButtonSave.Click += new System.EventHandler(this.toolStripButtonSave_Click);
            // 
            // toolStripButtonUndo
            // 
            this.toolStripButtonUndo.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            //this.toolStripButtonUndo.Image = global::");
            
            #line 68 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\EditDataFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write(@".Properties.Resources.Undo_16x;
            this.toolStripButtonUndo.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonUndo.Name = ""toolStripButtonUndo"";
            this.toolStripButtonUndo.Size = new System.Drawing.Size(40, 22);
            this.toolStripButtonUndo.Text = ""Undo"";
            this.toolStripButtonUndo.Click += new System.EventHandler(this.toolStripButtonUndo_Click);
            // 
            // EditDataForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(234, 276);
            this.Controls.Add(this.toolStrip1);
            this.Name = ""EditDataForm"";
            this.Text = ""EditDataForm"";
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton toolStripButtonSave;
        private System.Windows.Forms.ToolStripButton toolStripButtonUndo;
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
