// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SEP_CRUD.Entities;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EditFormTemplate : SharedFormTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
 var EntityName = Table.BindingName; 
            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentModel;\r\nu" +
                    "sing System.Data;\r\nusing System.Drawing;\r\nusing System.Runtime.CompilerServices;" +
                    "\r\nusing System.Text;\r\nusing System.Windows.Forms;\r\nusing ");
            
            #line 16 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.ProjectOwner.DefaultModelNamespaces));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 18 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
 Write(Generator.Namespace); 
            
            #line default
            #line hidden
            this.Write("{\r\n    public partial class Edit");
            
            #line 20 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Form : Edit");
            
            #line 20 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("FormBase\r\n    {\r\n        public Edit");
            
            #line 22 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Form()\r\n        {\r\n            InitializeComponent();\r\n        }\r\n\r\n\t\t protected " +
                    "override void InitBinder(");
            
            #line 27 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            base.InitBinder(entity);\r\n");
            
            #line 30 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"

    for (int i = 0; i < Table.Count; i++)
    {
		WriteDataBinding(Table[i]);
    } 

            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n        }\r\n\r\n        protected override void OnFormLoaded(object sender, For" +
                    "mType e)\r\n        {\r\n            if (e == FormType.FormAdd)\r\n            {\r\n");
            
            #line 42 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"

    for (int i = 0; i < Table.Count; i++)
    {
		Column c = Table[i];
		if (c.IsAbleBindingToTextBoxControl() && c.IsPrimaryKey)
			setReadOnlyTextBox(c.BindingName, "false");
    } 

            
            #line default
            #line hidden
            this.Write("\r\n            }\r\n            else if (e == FormType.FormUpdate)\r\n            {\r\n");
            
            #line 54 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"

    for (int i = 0; i < Table.Count; i++)
    {
		Column c = Table[i];
		if (c.IsAbleBindingToTextBoxControl() && c.IsPrimaryKey)
			setReadOnlyTextBox(c.BindingName, "true");
    } 

            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n    }\r\n\r\n    // This additional inheritance is required" +
                    " to avoid a WinForms bug,\r\n    // which does not allow using generic classes as " +
                    "base classes for forms and uer controls.\r\n\t\r\n    public class Edit");
            
            #line 69 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("FormBase: EditDataForm<");
            
            #line 69 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(", Edit");
            
            #line 69 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Form> { }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 71 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
 
private void WriteDataBinding(Column c)
{
	var name = c.BindingName;
	if (c.IsAbleBindingToTextBoxControl())
    {

        
        #line default
        #line hidden
        
        #line 77 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write("\t\t\ttextBox");

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(name));

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(".DataBindings.Add(\"Text\", bindingSourceItem, \"");

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(name));

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write("\", true, DataSourceUpdateMode.OnValidation, string.Empty);\r\n");

        
        #line default
        #line hidden
        
        #line 79 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
 
    }

	if (c.IsAbleBindingToDateTimePicker())
    {

        
        #line default
        #line hidden
        
        #line 84 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write("\t\t\tdateTimePicker");

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(name));

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(".DataBindings.Add(\"Value\", bindingSourceItem, \"");

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(name));

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write("\", true, DataSourceUpdateMode.OnValidation, DateTime.Now);\r\n");

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
 }
}

        
        #line default
        #line hidden
        
        #line 89 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"

void setReadOnlyTextBox(string name, string b)
{

        
        #line default
        #line hidden
        
        #line 92 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write("\t\t\t\ttextBox");

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(name));

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(".ReadOnly = ");

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(b));

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\EditFormTemplate.tt"

} 

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
