// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\ItemTableDesignerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ItemTableDesignerTemplate : SharedFormDesignerTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\ItemTableDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    partial class ItemTableUserControl\r\n    {\r\n        /// <summary> \r\n     " +
                    "   /// Required designer variable.\r\n        /// </summary>\r\n        private Syst" +
                    "em.ComponentModel.IContainer components = null;\r\n\r\n        /// <summary> \r\n     " +
                    "   /// Clean up any resources being used.\r\n        /// </summary>\r\n        /// <" +
                    "param name=\"disposing\">true if managed resources should be disposed; otherwise, " +
                    "false.</param>\r\n        protected override void Dispose(bool disposing)\r\n       " +
                    " {\r\n            if (disposing && (components != null))\r\n            {\r\n         " +
                    "       components.Dispose();\r\n            }\r\n            base.Dispose(disposing)" +
                    ";\r\n        }\r\n\r\n        #region Component Designer generated code\r\n\r\n        ///" +
                    " <summary> \r\n        /// Required method for Designer support - do not modify \r\n" +
                    "        /// the contents of this method with the code editor.\r\n        /// </sum" +
                    "mary>\r\n        private void InitializeComponent()\r\n        {\r\n            this.T" +
                    "itle = new System.Windows.Forms.Label();\r\n            this.InsidePanel = new Sys" +
                    "tem.Windows.Forms.Panel();\r\n            this.Description = new System.Windows.Fo" +
                    "rms.Label();\r\n            this.InsidePanel.SuspendLayout();\r\n            this.Su" +
                    "spendLayout();\r\n            // \r\n            // Title\r\n            // \r\n        " +
                    "    this.Title.BackColor = System.Drawing.Color.Transparent;\r\n            this.T" +
                    "itle.Dock = System.Windows.Forms.DockStyle.Top;\r\n            this.Title.Font = n" +
                    "ew System.Drawing.Font(\"Segoe UI Semibold\", 24F, System.Drawing.FontStyle.Bold, " +
                    "System.Drawing.GraphicsUnit.Point, ((byte)(0)));\r\n            this.Title.ForeCol" +
                    "or = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(11))))," +
                    " ((int)(((byte)(11)))));\r\n            this.Title.Location = new System.Drawing.P" +
                    "oint(0, 0);\r\n            this.Title.Name = \"Title\";\r\n            this.Title.Padd" +
                    "ing = new System.Windows.Forms.Padding(8);\r\n            this.Title.Size = new Sy" +
                    "stem.Drawing.Size(223, 152);\r\n            this.Title.TabIndex = 0;\r\n            " +
                    "this.Title.Text = \"Giaovien\";\r\n            this.Title.TextAlign = System.Drawing" +
                    ".ContentAlignment.MiddleCenter;\r\n            this.Title.MouseDown += new System." +
                    "Windows.Forms.MouseEventHandler(this.OnMouseDownPanel);\r\n            this.Title." +
                    "MouseLeave += new System.EventHandler(this.OnMouseLeavePanel);\r\n            this" +
                    ".Title.MouseMove += new System.Windows.Forms.MouseEventHandler(this.OnMouseMoveP" +
                    "anel);\r\n            // \r\n            // InsidePanel\r\n            // \r\n          " +
                    "  this.InsidePanel.BackColor = System.Drawing.Color.White;\r\n            this.Ins" +
                    "idePanel.Controls.Add(this.Description);\r\n            this.InsidePanel.Controls." +
                    "Add(this.Title);\r\n            this.InsidePanel.Cursor = System.Windows.Forms.Cur" +
                    "sors.Hand;\r\n            this.InsidePanel.Location = new System.Drawing.Point(1, " +
                    "1);\r\n            this.InsidePanel.Margin = new System.Windows.Forms.Padding(16);" +
                    "\r\n            this.InsidePanel.Name = \"InsidePanel\";\r\n            this.InsidePan" +
                    "el.Size = new System.Drawing.Size(223, 218);\r\n            this.InsidePanel.TabIn" +
                    "dex = 1;\r\n            this.InsidePanel.MouseDown += new System.Windows.Forms.Mou" +
                    "seEventHandler(this.OnMouseDownPanel);\r\n            this.InsidePanel.MouseLeave " +
                    "+= new System.EventHandler(this.OnMouseLeavePanel);\r\n            this.InsidePane" +
                    "l.MouseMove += new System.Windows.Forms.MouseEventHandler(this.OnMouseMovePanel)" +
                    ";\r\n            // \r\n            // Description\r\n            // \r\n            thi" +
                    "s.Description.BackColor = System.Drawing.Color.Transparent;\r\n            this.De" +
                    "scription.Dock = System.Windows.Forms.DockStyle.Bottom;\r\n            this.Descri" +
                    "ption.Font = new System.Drawing.Font(\"Segoe UI Semibold\", 9F, System.Drawing.Fon" +
                    "tStyle.Bold);\r\n            this.Description.ForeColor = System.Drawing.Color.Fro" +
                    "mArgb(((int)(((byte)(11)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));\r\n   " +
                    "         this.Description.Location = new System.Drawing.Point(0, 155);\r\n        " +
                    "    this.Description.Name = \"Description\";\r\n            this.Description.Padding" +
                    " = new System.Windows.Forms.Padding(8, 0, 8, 0);\r\n            this.Description.S" +
                    "ize = new System.Drawing.Size(223, 63);\r\n            this.Description.TabIndex =" +
                    " 1;\r\n            this.Description.Text = \"From table \\\"GIAOVIEN\\\"\";\r\n           " +
                    " this.Description.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;\r\n   " +
                    "         this.Description.MouseDown += new System.Windows.Forms.MouseEventHandle" +
                    "r(this.OnMouseDownPanel);\r\n            this.Description.MouseLeave += new System" +
                    ".EventHandler(this.OnMouseLeavePanel);\r\n            this.Description.MouseMove +" +
                    "= new System.Windows.Forms.MouseEventHandler(this.OnMouseMovePanel);\r\n          " +
                    "  // \r\n            // ItemTableUserControl\r\n            // \r\n            this.Au" +
                    "toScaleDimensions = new System.Drawing.SizeF(8F, 16F);\r\n            this.AutoSca" +
                    "leMode = System.Windows.Forms.AutoScaleMode.Font;\r\n            this.BackColor = " +
                    "System.Drawing.Color.Gainsboro;\r\n            this.Controls.Add(this.InsidePanel)" +
                    ";\r\n            this.ForeColor = System.Drawing.Color.White;\r\n            this.Ma" +
                    "rgin = new System.Windows.Forms.Padding(16);\r\n            this.Name = \"ItemTable" +
                    "UserControl\";\r\n            this.Size = new System.Drawing.Size(225, 225);\r\n     " +
                    "       this.InsidePanel.ResumeLayout(false);\r\n            this.ResumeLayout(fals" +
                    "e);\r\n\r\n        }\r\n\r\n        #endregion\r\n\r\n        private System.Windows.Forms.L" +
                    "abel Title;\r\n        private System.Windows.Forms.Panel InsidePanel;\r\n        pr" +
                    "ivate System.Windows.Forms.Label Description;\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
