// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Kim Ninh\Documents\Visual Studio 2017\Projects\sep_crud\SEP_CRUD\Template\Form\LoginFormDesignerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class LoginFormDesignerTemplate : SharedFormDesignerGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "C:\Users\Kim Ninh\Documents\Visual Studio 2017\Projects\sep_crud\SEP_CRUD\Template\Form\LoginFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    partial class LoginForm\r\n    {\r\n        /// <summary>\r\n        /// Requi" +
                    "red designer variable.\r\n        /// </summary>\r\n        private System.Component" +
                    "Model.IContainer components = null;\r\n\r\n        /// <summary>\r\n        /// Clean " +
                    "up any resources being used.\r\n        /// </summary>\r\n        /// <param name=\"d" +
                    "isposing\">true if managed resources should be disposed; otherwise, false.</param" +
                    ">\r\n        protected override void Dispose(bool disposing)\r\n        {\r\n         " +
                    "   if (disposing && (components != null))\r\n            {\r\n                compon" +
                    "ents.Dispose();\r\n            }\r\n            base.Dispose(disposing);\r\n        }\r" +
                    "\n\r\n        #region Windows Form Designer generated code\r\n\r\n        /// <summary>" +
                    "\r\n        /// Required method for Designer support - do not modify\r\n        /// " +
                    "the contents of this method with the code editor.\r\n        /// </summary>\r\n     " +
                    "   private void InitializeComponent()\r\n        {\r\n            this.components = " +
                    "new System.ComponentModel.Container();\r\n            System.Windows.Forms.Label l" +
                    "abel1;\r\n            System.Windows.Forms.Label label2;\r\n            System.Windo" +
                    "ws.Forms.Label label3;\r\n            this.comboBoxServerList = new System.Windows" +
                    ".Forms.ComboBox();\r\n            this.loginInfoBindingSource = new System.Windows" +
                    ".Forms.BindingSource(this.components);\r\n            this.textBoxLogin = new Syst" +
                    "em.Windows.Forms.TextBox();\r\n            this.textBoxPassword = new System.Windo" +
                    "ws.Forms.TextBox();\r\n            this.buttonConnect = new System.Windows.Forms.B" +
                    "utton();\r\n            this.buttonCancel = new System.Windows.Forms.Button();\r\n  " +
                    "          label1 = new System.Windows.Forms.Label();\r\n            label2 = new S" +
                    "ystem.Windows.Forms.Label();\r\n            label3 = new System.Windows.Forms.Labe" +
                    "l();\r\n            ((System.ComponentModel.ISupportInitialize)(this.loginInfoBind" +
                    "ingSource)).BeginInit();\r\n            this.SuspendLayout();\r\n            // \r\n  " +
                    "          // label1\r\n            // \r\n            label1.AutoSize = true;\r\n     " +
                    "       label1.Location = new System.Drawing.Point(22, 45);\r\n            label1.N" +
                    "ame = \"label1\";\r\n            label1.Size = new System.Drawing.Size(72, 13);\r\n   " +
                    "         label1.TabIndex = 0;\r\n            label1.Text = \"Server Name:\";\r\n      " +
                    "      // \r\n            // label2\r\n            // \r\n            label2.Anchor = (" +
                    "(System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | Sy" +
                    "stem.Windows.Forms.AnchorStyles.Bottom) \r\n            | System.Windows.Forms.Anc" +
                    "horStyles.Left)));\r\n            label2.AutoSize = true;\r\n            label2.Loca" +
                    "tion = new System.Drawing.Point(38, 72);\r\n            label2.Name = \"label2\";\r\n " +
                    "           label2.Size = new System.Drawing.Size(36, 13);\r\n            label2.Ta" +
                    "bIndex = 0;\r\n            label2.Text = \"Login:\";\r\n            // \r\n            /" +
                    "/ label3\r\n            // \r\n            label3.Anchor = ((System.Windows.Forms.An" +
                    "chorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.Ancho" +
                    "rStyles.Bottom) \r\n            | System.Windows.Forms.AnchorStyles.Left)));\r\n    " +
                    "        label3.AutoSize = true;\r\n            label3.Location = new System.Drawin" +
                    "g.Point(38, 98);\r\n            label3.Name = \"label3\";\r\n            label3.Size =" +
                    " new System.Drawing.Size(56, 13);\r\n            label3.TabIndex = 0;\r\n           " +
                    " label3.Text = \"Password:\";\r\n            // \r\n            // comboBoxServerList\r" +
                    "\n            // \r\n            this.comboBoxServerList.Anchor = ((System.Windows." +
                    "Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Form" +
                    "s.AnchorStyles.Right)));\r\n            this.comboBoxServerList.FormattingEnabled " +
                    "= true;\r\n            this.comboBoxServerList.Location = new System.Drawing.Point" +
                    "(145, 42);\r\n            this.comboBoxServerList.Name = \"comboBoxServerList\";\r\n  " +
                    "          this.comboBoxServerList.Size = new System.Drawing.Size(222, 21);\r\n    " +
                    "        this.comboBoxServerList.TabIndex = 1;\r\n            this.comboBoxServerLi" +
                    "st.DropDown += new System.EventHandler(this.comboBoxServerList_DropDown);\r\n     " +
                    "       // \r\n            // textBoxLogin\r\n            // \r\n            this.textB" +
                    "oxLogin.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.Anc" +
                    "horStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) \r\n            | System" +
                    ".Windows.Forms.AnchorStyles.Right)));\r\n            this.textBoxLogin.Location = " +
                    "new System.Drawing.Point(145, 69);\r\n            this.textBoxLogin.Name = \"textBo" +
                    "xLogin\";\r\n            this.textBoxLogin.Size = new System.Drawing.Size(222, 20);" +
                    "\r\n            this.textBoxLogin.TabIndex = 2;\r\n            // \r\n            // t" +
                    "extBoxPassword\r\n            // \r\n            this.textBoxPassword.Anchor = ((Sys" +
                    "tem.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System" +
                    ".Windows.Forms.AnchorStyles.Bottom) \r\n            | System.Windows.Forms.AnchorS" +
                    "tyles.Right)));\r\n            this.textBoxPassword.Location = new System.Drawing." +
                    "Point(145, 95);\r\n            this.textBoxPassword.Name = \"textBoxPassword\";\r\n   " +
                    "         this.textBoxPassword.PasswordChar = \'*\';\r\n            this.textBoxPassw" +
                    "ord.Size = new System.Drawing.Size(222, 20);\r\n            this.textBoxPassword.T" +
                    "abIndex = 3;\r\n            // \r\n            // buttonConnect\r\n            // \r\n  " +
                    "          this.buttonConnect.Anchor = ((System.Windows.Forms.AnchorStyles)((Syst" +
                    "em.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right))" +
                    ");\r\n            this.buttonConnect.Location = new System.Drawing.Point(204, 137)" +
                    ";\r\n            this.buttonConnect.Name = \"buttonConnect\";\r\n            this.butt" +
                    "onConnect.Size = new System.Drawing.Size(73, 23);\r\n            this.buttonConnec" +
                    "t.TabIndex = 4;\r\n            this.buttonConnect.Text = \"Connect\";\r\n            t" +
                    "his.buttonConnect.UseVisualStyleBackColor = true;\r\n            this.buttonConnec" +
                    "t.Click += new System.EventHandler(this.buttonConnect_Click);\r\n            // \r\n" +
                    "            // buttonCancel\r\n            // \r\n            this.buttonCancel.Anch" +
                    "or = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bot" +
                    "tom | System.Windows.Forms.AnchorStyles.Right)));\r\n            this.buttonCancel" +
                    ".Location = new System.Drawing.Point(292, 137);\r\n            this.buttonCancel.N" +
                    "ame = \"buttonCancel\";\r\n            this.buttonCancel.Size = new System.Drawing.S" +
                    "ize(75, 23);\r\n            this.buttonCancel.TabIndex = 5;\r\n            this.butt" +
                    "onCancel.Text = \"Cancel\";\r\n            this.buttonCancel.UseVisualStyleBackColor" +
                    " = true;\r\n            this.buttonCancel.Click += new System.EventHandler(this.bu" +
                    "ttonCancel_Click);\r\n            // \r\n            // LoginDBFrom1\r\n            //" +
                    " \r\n            this.AcceptButton = this.buttonConnect;\r\n            this.AutoSca" +
                    "leDimensions = new System.Drawing.SizeF(6F, 13F);\r\n            this.ClientSize =" +
                    " new System.Drawing.Size(396, 181);\r\n            this.Controls.Add(this.buttonCa" +
                    "ncel);\r\n            this.Controls.Add(this.buttonConnect);\r\n            this.Con" +
                    "trols.Add(this.textBoxPassword);\r\n            this.Controls.Add(this.textBoxLogi" +
                    "n);\r\n            this.Controls.Add(this.comboBoxServerList);\r\n            this.C" +
                    "ontrols.Add(label3);\r\n            this.Controls.Add(label2);\r\n            this.C" +
                    "ontrols.Add(label1);\r\n            this.Location = new System.Drawing.Point(0, 0)" +
                    ";\r\n            this.MaximizeBox = false;\r\n            this.MinimizeBox = false;\r" +
                    "\n            this.Name = \"LoginForm\";\r\n            this.Text = \"Login to DB Serv" +
                    "er\";\r\n            this.WindowState = System.Windows.Forms.FormWindowState.Normal" +
                    ";\r\n            ((System.ComponentModel.ISupportInitialize)(this.loginInfoBinding" +
                    "Source)).EndInit();\r\n            this.ResumeLayout(false);\r\n            this.Per" +
                    "formLayout();\r\n\r\n        }\r\n\r\n        #endregion\r\n\r\n        private System.Windo" +
                    "ws.Forms.ComboBox comboBoxServerList;\r\n        private System.Windows.Forms.Text" +
                    "Box textBoxLogin;\r\n        private System.Windows.Forms.TextBox textBoxPassword;" +
                    "\r\n        private System.Windows.Forms.Button buttonConnect;\r\n        private Sy" +
                    "stem.Windows.Forms.Button buttonCancel;\r\n        private System.Windows.Forms.Bi" +
                    "ndingSource loginInfoBindingSource;\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
