// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\SelectTableFormDesignerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SelectTableFormDesignerTemplate : SharedFormDesignerTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\SelectTableFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    partial class SelectTableForm\r\n    {\r\n        /// <summary>\r\n        ///" +
                    " Required designer variable.\r\n        /// </summary>\r\n        private System.Com" +
                    "ponentModel.IContainer components = null;\r\n\r\n        /// <summary>\r\n        /// " +
                    "Clean up any resources being used.\r\n        /// </summary>\r\n        /// <param n" +
                    "ame=\"disposing\">true if managed resources should be disposed; otherwise, false.<" +
                    "/param>\r\n        protected override void Dispose(bool disposing)\r\n        {\r\n   " +
                    "         if (disposing && (components != null))\r\n            {\r\n                " +
                    "components.Dispose();\r\n            }\r\n            base.Dispose(disposing);\r\n    " +
                    "    }\r\n\r\n        #region Windows Form Designer generated code\r\n\r\n        /// <su" +
                    "mmary>\r\n        /// Required method for Designer support - do not modify\r\n      " +
                    "  /// the contents of this method with the code editor.\r\n        /// </summary>\r" +
                    "\n        private void InitializeComponent()\r\n        {\r\n            this.listBox" +
                    "DBTableName = new System.Windows.Forms.ListBox();\r\n            this.buttonViewTa" +
                    "ble = new System.Windows.Forms.Button();\r\n            this.toolStrip1 = new Syst" +
                    "em.Windows.Forms.ToolStrip();\r\n            this.toolStripButtonConnect = new Sys" +
                    "tem.Windows.Forms.ToolStripButton();\r\n            this.toolStrip1.SuspendLayout(" +
                    ");\r\n            this.SuspendLayout();\r\n            // \r\n            // listBoxDB" +
                    "TableName\r\n            // \r\n            this.listBoxDBTableName.BorderStyle = Sy" +
                    "stem.Windows.Forms.BorderStyle.None;\r\n            this.listBoxDBTableName.Format" +
                    "tingEnabled = true;\r\n            this.listBoxDBTableName.ItemHeight = 16;\r\n     " +
                    "       this.listBoxDBTableName.Location = new System.Drawing.Point(0, 43);\r\n    " +
                    "        this.listBoxDBTableName.Margin = new System.Windows.Forms.Padding(4, 4, " +
                    "4, 4);\r\n            this.listBoxDBTableName.Name = \"listBoxDBTableName\";\r\n      " +
                    "      this.listBoxDBTableName.Size = new System.Drawing.Size(431, 512);\r\n       " +
                    "     this.listBoxDBTableName.TabIndex = 1;\r\n            // \r\n            // butt" +
                    "onViewTable\r\n            // \r\n            this.buttonViewTable.Anchor = ((System" +
                    ".Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Wi" +
                    "ndows.Forms.AnchorStyles.Bottom) \r\n            | System.Windows.Forms.AnchorStyl" +
                    "es.Right)));\r\n            this.buttonViewTable.BackColor = System.Drawing.Color." +
                    "White;\r\n            this.buttonViewTable.Enabled = false;\r\n            this.butt" +
                    "onViewTable.Font = new System.Drawing.Font(\"Microsoft Sans Serif\", 11.25F, Syste" +
                    "m.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));\r\n " +
                    "           this.buttonViewTable.ForeColor = System.Drawing.Color.Black;\r\n       " +
                    "     this.buttonViewTable.Location = new System.Drawing.Point(129, 574);\r\n      " +
                    "      this.buttonViewTable.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4)" +
                    ";\r\n            this.buttonViewTable.Name = \"buttonViewTable\";\r\n            this." +
                    "buttonViewTable.Size = new System.Drawing.Size(155, 48);\r\n            this.butto" +
                    "nViewTable.TabIndex = 2;\r\n            this.buttonViewTable.Text = \"View Table\";\r" +
                    "\n            this.buttonViewTable.UseVisualStyleBackColor = false;\r\n            " +
                    "this.buttonViewTable.Click += new System.EventHandler(this.buttonViewTable_Click" +
                    ");\r\n            // \r\n            // toolStrip1\r\n            // \r\n            thi" +
                    "s.toolStrip1.BackColor = System.Drawing.Color.White;\r\n            this.toolStrip" +
                    "1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;\r\n            th" +
                    "is.toolStrip1.ImageScalingSize = new System.Drawing.Size(20, 20);\r\n            t" +
                    "his.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {\r\n      " +
                    "      this.toolStripButtonConnect});\r\n            this.toolStrip1.Location = new" +
                    " System.Drawing.Point(0, 0);\r\n            this.toolStrip1.Name = \"toolStrip1\";\r\n" +
                    "            this.toolStrip1.Size = new System.Drawing.Size(430, 44);\r\n          " +
                    "  this.toolStrip1.TabIndex = 3;\r\n            this.toolStrip1.Text = \"toolStrip1\"" +
                    ";\r\n            // \r\n            // toolStripButtonConnect\r\n            // \r\n    " +
                    "        this.toolStripButtonConnect.DisplayStyle = System.Windows.Forms.ToolStri" +
                    "pItemDisplayStyle.Text;\r\n            this.toolStripButtonConnect.Font = new Syst" +
                    "em.Drawing.Font(\"Segoe UI\", 16F);\r\n            this.toolStripButtonConnect.Image" +
                    "TransparentColor = System.Drawing.Color.Magenta;\r\n            this.toolStripButt" +
                    "onConnect.Name = \"toolStripButtonConnect\";\r\n            this.toolStripButtonConn" +
                    "ect.Size = new System.Drawing.Size(349, 41);\r\n            this.toolStripButtonCo" +
                    "nnect.Text = \"Connect to Database Server\";\r\n            this.toolStripButtonConn" +
                    "ect.TextImageRelation = System.Windows.Forms.TextImageRelation.TextBeforeImage;\r" +
                    "\n            this.toolStripButtonConnect.Click += new System.EventHandler(this.t" +
                    "oolStripButtonConnect_Click);\r\n            // \r\n            // SelectTableForm\r\n" +
                    "            // \r\n            this.AcceptButton = this.buttonViewTable;\r\n        " +
                    "    this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);\r\n            t" +
                    "his.BackColor = System.Drawing.Color.White;\r\n            this.ClientSize = new S" +
                    "ystem.Drawing.Size(430, 635);\r\n            this.Controls.Add(this.toolStrip1);\r\n" +
                    "            this.Controls.Add(this.buttonViewTable);\r\n            this.Controls." +
                    "Add(this.listBoxDBTableName);\r\n            this.Margin = new System.Windows.Form" +
                    "s.Padding(5, 5, 5, 5);\r\n            this.MaximumSize = new System.Drawing.Size(4" +
                    "48, 682);\r\n            this.MinimumSize = new System.Drawing.Size(448, 682);\r\n  " +
                    "          this.Name = \"SelectTableForm\";\r\n            this.ShowIcon = false;\r\n  " +
                    "          this.Text = \"Dashboard\";\r\n            this.Shown += new System.EventHa" +
                    "ndler(this.SelectDBTableForm_Shown);\r\n            this.toolStrip1.ResumeLayout(f" +
                    "alse);\r\n            this.toolStrip1.PerformLayout();\r\n            this.ResumeLay" +
                    "out(false);\r\n            this.PerformLayout();\r\n\r\n        }\r\n\r\n        #endregio" +
                    "n\r\n\r\n        private System.Windows.Forms.ListBox listBoxDBTableName;\r\n        p" +
                    "rivate System.Windows.Forms.Button buttonViewTable;\r\n        private System.Wind" +
                    "ows.Forms.ToolStrip toolStrip1;\r\n        private System.Windows.Forms.ToolStripB" +
                    "utton toolStripButtonConnect;\r\n    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
