// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\SelectTableFormDesignerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SelectTableFormDesignerTemplate : SharedFormDesignerGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\SelectTableFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    partial class SelectTableForm\r\n    {\r\n        /// <summary>\r\n        ///" +
                    " Required designer variable.\r\n        /// </summary>\r\n        private System.Com" +
                    "ponentModel.IContainer components = null;\r\n\r\n        /// <summary>\r\n        /// " +
                    "Clean up any resources being used.\r\n        /// </summary>\r\n        /// <param n" +
                    "ame=\"disposing\">true if managed resources should be disposed; otherwise, false.<" +
                    "/param>\r\n        protected override void Dispose(bool disposing)\r\n        {\r\n   " +
                    "         if (disposing && (components != null))\r\n            {\r\n                " +
                    "components.Dispose();\r\n            }\r\n            base.Dispose(disposing);\r\n    " +
                    "    }\r\n\r\n        #region Windows Form Designer generated code\r\n\r\n        /// <su" +
                    "mmary>\r\n        /// Required method for Designer support - do not modify\r\n      " +
                    "  /// the contents of this method with the code editor.\r\n        /// </summary>\r" +
                    "\n        private void InitializeComponent()\r\n        {\r\n            this.listBox" +
                    "DBTableName = new System.Windows.Forms.ListBox();\r\n            this.buttonViewTa" +
                    "ble = new System.Windows.Forms.Button();\r\n            this.toolStrip1 = new Syst" +
                    "em.Windows.Forms.ToolStrip();\r\n            this.toolStripButtonConnect = new Sys" +
                    "tem.Windows.Forms.ToolStripButton();\r\n            this.toolStrip1.SuspendLayout(" +
                    ");\r\n            this.SuspendLayout();\r\n            // \r\n            // listBoxDB" +
                    "TableName\r\n            // \r\n            this.listBoxDBTableName.Anchor = ((Syste" +
                    "m.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System." +
                    "Windows.Forms.AnchorStyles.Bottom) \r\n            | System.Windows.Forms.AnchorSt" +
                    "yles.Left) \r\n            | System.Windows.Forms.AnchorStyles.Right)));\r\n        " +
                    "    this.listBoxDBTableName.FormattingEnabled = true;\r\n            this.listBoxD" +
                    "BTableName.Location = new System.Drawing.Point(12, 74);\r\n            this.listBo" +
                    "xDBTableName.Name = \"listBoxDBTableName\";\r\n            this.listBoxDBTableName.S" +
                    "ize = new System.Drawing.Size(312, 420);\r\n            this.listBoxDBTableName.Ta" +
                    "bIndex = 1;\r\n            // \r\n            // buttonViewTable\r\n            // \r\n " +
                    "           this.buttonViewTable.Anchor = ((System.Windows.Forms.AnchorStyles)(((" +
                    "System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom" +
                    ") \r\n            | System.Windows.Forms.AnchorStyles.Right)));\r\n            this." +
                    "buttonViewTable.Enabled = false;\r\n            this.buttonViewTable.Location = ne" +
                    "w System.Drawing.Point(249, 26);\r\n            this.buttonViewTable.Name = \"butto" +
                    "nViewTable\";\r\n            this.buttonViewTable.Size = new System.Drawing.Size(75" +
                    ", 22);\r\n            this.buttonViewTable.TabIndex = 2;\r\n            this.buttonV" +
                    "iewTable.Text = \"View Table\";\r\n            this.buttonViewTable.UseVisualStyleBa" +
                    "ckColor = true;\r\n            this.buttonViewTable.Click += new System.EventHandl" +
                    "er(this.buttonViewTable_Click);\r\n            // \r\n            // toolStrip1\r\n   " +
                    "         // \r\n            this.toolStrip1.Items.AddRange(new System.Windows.Form" +
                    "s.ToolStripItem[] {\r\n            this.toolStripButtonConnect});\r\n            thi" +
                    "s.toolStrip1.Location = new System.Drawing.Point(0, 0);\r\n            this.toolSt" +
                    "rip1.Name = \"toolStrip1\";\r\n            this.toolStrip1.Size = new System.Drawing" +
                    ".Size(336, 25);\r\n            this.toolStrip1.TabIndex = 3;\r\n            this.too" +
                    "lStrip1.Text = \"toolStrip1\";\r\n            // \r\n            // toolStripButtonCon" +
                    "nect\r\n            // \r\n            this.toolStripButtonConnect.DisplayStyle = Sy" +
                    "stem.Windows.Forms.ToolStripItemDisplayStyle.Text;\r\n            //this.toolStrip" +
                    "ButtonConnect.Image = global::DemoGeneratedProject.Properties.Resources.Connect_" +
                    "16x;\r\n            this.toolStripButtonConnect.ImageTransparentColor = System.Dra" +
                    "wing.Color.Magenta;\r\n            this.toolStripButtonConnect.Name = \"toolStripBu" +
                    "ttonConnect\";\r\n            this.toolStripButtonConnect.Size = new System.Drawing" +
                    ".Size(123, 22);\r\n            this.toolStripButtonConnect.Text = \"Connect to DB S" +
                    "erver\";\r\n            this.toolStripButtonConnect.Click += new System.EventHandle" +
                    "r(this.toolStripButtonConnect_Click);\r\n            // \r\n            // SelectDBT" +
                    "ableForm\r\n            // \r\n            this.AcceptButton = this.buttonViewTable;" +
                    "\r\n            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);\r\n   " +
                    "         this.ClientSize = new System.Drawing.Size(336, 506);\r\n            this." +
                    "Controls.Add(this.toolStrip1);\r\n            this.Controls.Add(this.buttonViewTab" +
                    "le);\r\n            this.Controls.Add(this.listBoxDBTableName);\r\n            this." +
                    "Location = new System.Drawing.Point(0, 0);\r\n            this.Name = \"SelectDBTab" +
                    "leForm\";\r\n            this.Text = \"Select Table\";\r\n            this.WindowState " +
                    "= System.Windows.Forms.FormWindowState.Normal;\r\n            this.Shown += new Sy" +
                    "stem.EventHandler(this.SelectDBTableForm_Shown);\r\n            this.toolStrip1.Re" +
                    "sumeLayout(false);\r\n            this.toolStrip1.PerformLayout();\r\n            th" +
                    "is.ResumeLayout(false);\r\n            this.PerformLayout();\r\n\r\n        }\r\n\r\n     " +
                    "   #endregion\r\n\r\n        private System.Windows.Forms.ListBox listBoxDBTableName" +
                    ";\r\n        private System.Windows.Forms.Button buttonViewTable;\r\n        private" +
                    " System.Windows.Forms.ToolStrip toolStrip1;\r\n        private System.Windows.Form" +
                    "s.ToolStripButton toolStripButtonConnect;\r\n    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
