// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\ViewDataFormTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ViewDataFormTemplate : SharedFormGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentModel;\r\nu" +
                    "sing System.Data;\r\nusing System.Drawing;\r\nusing System.Text;\r\nusing System.Windo" +
                    "ws.Forms;\r\nusing ");
            
            #line 13 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\ViewDataFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.ProjectOwner.DefaultModelNamespaces));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 15 "F:\Library\IT\Subject\Design Pattern\SEP_CRUD2\SEP_CRUD\SEP_CRUD\Template\Form\ViewDataFormTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ViewDataFrom<E> : BaseForm\r\n        where E: BaseMo" +
                    "del\r\n    {\r\n        protected BindingList<E> bindingList;\r\n\r\n        public View" +
                    "DataFrom()\r\n        {\r\n            InitializeComponent();\r\n\r\n            editToo" +
                    "lStripMenuItem.Click += EditDataItem;\r\n            toolStripButtonEdit.Click += " +
                    "EditDataItem;\r\n\r\n            deleteToolStripMenuItem.Click += DeleteDataItem;\r\n " +
                    "           toolStripButtonDelete.Click += DeleteDataItem;\r\n        }\r\n\r\n        " +
                    "protected virtual void ViewDataFrom_Load(object sender, EventArgs e)\r\n        {\r" +
                    "\n            IList<E> list = initList();\r\n            bindingList = new BindingL" +
                    "ist<E>(list);\r\n            dataGridView1.DataSource = bindingList;\r\n        }\r\n\r" +
                    "\n        protected abstract IList<E> initList();\r\n\r\n        protected virtual vo" +
                    "id dataGridView1_CellDoubleClick(object sender, DataGridViewCellEventArgs e)\r\n  " +
                    "      {\r\n            var item = dataGridView1.CurrentRow.DataBoundItem;\r\n       " +
                    "     Edit((E) item);\r\n        }\r\n\r\n        protected virtual void toolStripButto" +
                    "nNew_Click(object sender, EventArgs e)\r\n        {\r\n            Add();\r\n        }" +
                    "\r\n\r\n        protected abstract void Add();\r\n        protected abstract void Edit" +
                    "(E item);\r\n\r\n        protected abstract void Delete(E item);\r\n\r\n        protecte" +
                    "d virtual void EditDataItem(object sender, EventArgs e)\r\n        {\r\n            " +
                    "var item = dataGridView1.CurrentRow.DataBoundItem;\r\n            Edit((E)item);\r\n" +
                    "        }\r\n\r\n        protected virtual void DeleteDataItem(object sender, EventA" +
                    "rgs e)\r\n        {\r\n            var item = dataGridView1.CurrentRow.DataBoundItem" +
                    ";\r\n            Delete((E)item);\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
