// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SEP_CRUD.Template.Form
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\ViewDataFormDesignerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ViewDataFormDesignerTemplate : SharedFormDesignerTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "C:\Users\trung\source\repos\SEP_CRUD\SEP_CRUD\Template\Form\ViewDataFormDesignerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n   abstract partial class ViewDataFrom<E>\r\n    {\r\n        /// <summary>\r\n   " +
                    "     /// Required designer variable.\r\n        /// </summary>\r\n        private Sy" +
                    "stem.ComponentModel.IContainer components = null;\r\n\r\n        /// <summary>\r\n    " +
                    "    /// Clean up any resources being used.\r\n        /// </summary>\r\n        /// " +
                    "<param name=\"disposing\">true if managed resources should be disposed; otherwise," +
                    " false.</param>\r\n        protected override void Dispose(bool disposing)\r\n      " +
                    "  {\r\n            if (disposing && (components != null))\r\n            {\r\n        " +
                    "        components.Dispose();\r\n            }\r\n            base.Dispose(disposing" +
                    ");\r\n        }\r\n\r\n        #region Windows Form Designer generated code\r\n\r\n       " +
                    " /// <summary>\r\n        /// Required method for Designer support - do not modify" +
                    "\r\n        /// the contents of this method with the code editor.\r\n        /// </s" +
                    "ummary>\r\n        private void InitializeComponent()\r\n        {\r\n            this" +
                    ".components = new System.ComponentModel.Container();\r\n            this.dataGridV" +
                    "iew1 = new System.Windows.Forms.DataGridView();\r\n            this.contextMenuStr" +
                    "ipDataGrid = new System.Windows.Forms.ContextMenuStrip(this.components);\r\n      " +
                    "      this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();" +
                    "\r\n            this.deleteToolStripMenuItem = new System.Windows.Forms.ToolStripM" +
                    "enuItem();\r\n            this.toolStrip1 = new System.Windows.Forms.ToolStrip();\r" +
                    "\n            this.toolStripButtonNew = new System.Windows.Forms.ToolStripButton(" +
                    ");\r\n            this.toolStripButtonEdit = new System.Windows.Forms.ToolStripBut" +
                    "ton();\r\n            this.toolStripButtonDelete = new System.Windows.Forms.ToolSt" +
                    "ripButton();\r\n            ((System.ComponentModel.ISupportInitialize)(this.dataG" +
                    "ridView1)).BeginInit();\r\n            this.contextMenuStripDataGrid.SuspendLayout" +
                    "();\r\n            this.toolStrip1.SuspendLayout();\r\n            this.SuspendLayou" +
                    "t();\r\n            // \r\n            // dataGridView1\r\n            // \r\n          " +
                    "  this.dataGridView1.AllowUserToAddRows = false;\r\n            this.dataGridView1" +
                    ".AllowUserToDeleteRows = false;\r\n            this.dataGridView1.AutoSizeColumnsM" +
                    "ode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;\r\n            th" +
                    "is.dataGridView1.BackgroundColor = System.Drawing.Color.White;\r\n            this" +
                    ".dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewCo" +
                    "lumnHeadersHeightSizeMode.AutoSize;\r\n            this.dataGridView1.ContextMenuS" +
                    "trip = this.contextMenuStripDataGrid;\r\n            this.dataGridView1.Dock = Sys" +
                    "tem.Windows.Forms.DockStyle.Fill;\r\n            this.dataGridView1.Location = new" +
                    " System.Drawing.Point(0, 0);\r\n            this.dataGridView1.Margin = new System" +
                    ".Windows.Forms.Padding(4, 4, 4, 4);\r\n            this.dataGridView1.Name = \"data" +
                    "GridView1\";\r\n            this.dataGridView1.ReadOnly = true;\r\n            this.d" +
                    "ataGridView1.Size = new System.Drawing.Size(1067, 519);\r\n            this.dataGr" +
                    "idView1.TabIndex = 0;\r\n            this.dataGridView1.CellDoubleClick += new Sys" +
                    "tem.Windows.Forms.DataGridViewCellEventHandler(this.dataGridView1_CellDoubleClic" +
                    "k);\r\n            // \r\n            // contextMenuStripDataGrid\r\n            // \r\n" +
                    "            this.contextMenuStripDataGrid.ImageScalingSize = new System.Drawing." +
                    "Size(20, 20);\r\n            this.contextMenuStripDataGrid.Items.AddRange(new Syst" +
                    "em.Windows.Forms.ToolStripItem[] {\r\n            this.editToolStripMenuItem,\r\n   " +
                    "         this.deleteToolStripMenuItem});\r\n            this.contextMenuStripDataG" +
                    "rid.Name = \"contextMenuStripDataGrid\";\r\n            this.contextMenuStripDataGri" +
                    "d.Size = new System.Drawing.Size(123, 52);\r\n            // \r\n            // edit" +
                    "ToolStripMenuItem\r\n            // \r\n            this.editToolStripMenuItem.Displ" +
                    "ayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;\r\n            this" +
                    ".editToolStripMenuItem.Name = \"editToolStripMenuItem\";\r\n            this.editToo" +
                    "lStripMenuItem.Size = new System.Drawing.Size(122, 24);\r\n            this.editTo" +
                    "olStripMenuItem.Text = \"Edit\";\r\n            // \r\n            // deleteToolStripM" +
                    "enuItem\r\n            // \r\n            this.deleteToolStripMenuItem.DisplayStyle " +
                    "= System.Windows.Forms.ToolStripItemDisplayStyle.Text;\r\n            this.deleteT" +
                    "oolStripMenuItem.Name = \"deleteToolStripMenuItem\";\r\n            this.deleteToolS" +
                    "tripMenuItem.Size = new System.Drawing.Size(122, 24);\r\n            this.deleteTo" +
                    "olStripMenuItem.Text = \"Delete\";\r\n            // \r\n            // toolStrip1\r\n  " +
                    "          // \r\n            this.toolStrip1.BackColor = System.Drawing.Color.Whit" +
                    "e;\r\n            this.toolStrip1.ImageScalingSize = new System.Drawing.Size(20, 2" +
                    "0);\r\n            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStr" +
                    "ipItem[] {\r\n            this.toolStripButtonNew,\r\n            this.toolStripButt" +
                    "onEdit,\r\n            this.toolStripButtonDelete});\r\n            this.toolStrip1." +
                    "Location = new System.Drawing.Point(0, 0);\r\n            this.toolStrip1.Name = \"" +
                    "toolStrip1\";\r\n            this.toolStrip1.Size = new System.Drawing.Size(1067, 2" +
                    "7);\r\n            this.toolStrip1.TabIndex = 2;\r\n            this.toolStrip1.Text" +
                    " = \"toolStrip1\";\r\n            // \r\n            // toolStripButtonNew\r\n          " +
                    "  // \r\n            this.toolStripButtonNew.DisplayStyle = System.Windows.Forms.T" +
                    "oolStripItemDisplayStyle.Text;\r\n            this.toolStripButtonNew.ImageTranspa" +
                    "rentColor = System.Drawing.Color.Magenta;\r\n            this.toolStripButtonNew.N" +
                    "ame = \"toolStripButtonNew\";\r\n            this.toolStripButtonNew.Size = new Syst" +
                    "em.Drawing.Size(90, 24);\r\n            this.toolStripButtonNew.Text = \"Create New" +
                    "\";\r\n            this.toolStripButtonNew.Click += new System.EventHandler(this.to" +
                    "olStripButtonNew_Click);\r\n            // \r\n            // toolStripButtonEdit\r\n " +
                    "           // \r\n            this.toolStripButtonEdit.DisplayStyle = System.Windo" +
                    "ws.Forms.ToolStripItemDisplayStyle.Text;\r\n            this.toolStripButtonEdit.I" +
                    "mageTransparentColor = System.Drawing.Color.Magenta;\r\n            this.toolStrip" +
                    "ButtonEdit.Name = \"toolStripButtonEdit\";\r\n            this.toolStripButtonEdit.S" +
                    "ize = new System.Drawing.Size(62, 24);\r\n            this.toolStripButtonEdit.Tex" +
                    "t = \"Update\";\r\n            // \r\n            // toolStripButtonDelete\r\n          " +
                    "  // \r\n            this.toolStripButtonDelete.DisplayStyle = System.Windows.Form" +
                    "s.ToolStripItemDisplayStyle.Text;\r\n            this.toolStripButtonDelete.ImageT" +
                    "ransparentColor = System.Drawing.Color.Magenta;\r\n            this.toolStripButto" +
                    "nDelete.Name = \"toolStripButtonDelete\";\r\n            this.toolStripButtonDelete." +
                    "Size = new System.Drawing.Size(57, 24);\r\n            this.toolStripButtonDelete." +
                    "Text = \"Delete\";\r\n            // \r\n            // ViewDataFrom\r\n            // \r" +
                    "\n            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);\r\n    " +
                    "        this.ClientSize = new System.Drawing.Size(1067, 519);\r\n            this." +
                    "Controls.Add(this.toolStrip1);\r\n            this.Controls.Add(this.dataGridView1" +
                    ");\r\n            this.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);\r\n   " +
                    "         this.Name = \"ViewDataFrom\";\r\n            this.Text = \"Dashboard\";\r\n    " +
                    "        this.Load += new System.EventHandler(this.ViewDataFrom_Load);\r\n         " +
                    "   ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();\r\n" +
                    "            this.contextMenuStripDataGrid.ResumeLayout(false);\r\n            this" +
                    ".toolStrip1.ResumeLayout(false);\r\n            this.toolStrip1.PerformLayout();\r\n" +
                    "            this.ResumeLayout(false);\r\n            this.PerformLayout();\r\n\r\n    " +
                    "    }\r\n\r\n        #endregion\r\n        private System.Windows.Forms.ToolStrip tool" +
                    "Strip1;\r\n        private System.Windows.Forms.ToolStripButton toolStripButtonNew" +
                    ";\r\n        private System.Windows.Forms.ToolStripButton toolStripButtonEdit;\r\n  " +
                    "      private System.Windows.Forms.ToolStripButton toolStripButtonDelete;\r\n     " +
                    "   private System.Windows.Forms.ContextMenuStrip contextMenuStripDataGrid;\r\n    " +
                    "    private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;\r\n     " +
                    "   private System.Windows.Forms.ToolStripMenuItem deleteToolStripMenuItem;\r\n    " +
                    "    protected System.Windows.Forms.DataGridView dataGridView1;\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
